apiVersion: apps/v1
kind: Deployment
metadata:
  name:  web
  namespace: deniz
  labels:
    app:  web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  web
    spec:
      containers:
      - name:  web
        image:  denizturkmen/rollingupdatev2:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  web
      restartPolicy: Always
